name: HACS Action

on:
  push:
  pull_request:

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    if: github.ref == 'refs/heads/main'
    steps:
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
